let moviedata = [
  {
    adult: false,
    backdrop_path: "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
    genres: ["Horror","Thriller"
    ],
    id: 760161,
    original_language: "en",
    original_title: "Orphan: First Kill",
    overview:
      "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
    popularity: 6835.317,
    poster_path: "/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg",
    release_date: "2022-07-27",
    title: "Orphan: First Kill",
    video: false,
    vote_average: 7,
    vote_count: 745,
  },
  {
    adult: false,
    backdrop_path: "/2RSirqZG949GuRwN38MYCIGG4Od.jpg",
    genres: [ "Thriller"
    ],
    id: 985939,
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights",
    popularity: 5402.19,
    poster_path: "/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
    release_date: "2022-08-11",
    title: "Fall",
    video: false,
    vote_average: 7.5,
    vote_count: 1053,
  },
  {
    adult: false,
    backdrop_path: "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
    genres: ["Fantasy", "Adventure", "Family"
    ],
    id: 532639,
    original_language: "en",
    original_title: "Pinocchio",
    overview:
      "A wooden puppet embarks on a thrilling adventure to become a real boy.",
    popularity: 2859.481,
    poster_path: "/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg",
    release_date: "2022-09-07",
    title: "Pinocchio",
    video: false,
    vote_average: 6.8,
    vote_count: 739,
  },
  {
    adult: false,
    backdrop_path: "/ybvm31ae8WW5O6411PDzwFlETuq.jpg",
    genres: ["Adventure", "Drama", "Horror"
    ],
    id: 760741,
    original_language: "en",
    original_title: "Beast",
    overview:
      "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    popularity: 2651.33,
    poster_path: "/iRV0IB5xQeOymuGGUBarTecQVAl.jpg",
    release_date: "2022-08-11",
    title: "Beast",
    video: false,
    vote_average: 7.1,
    vote_count: 497,
  },
  {
    adult: false,
    backdrop_path: "/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
    genres: ["Action", "Comedy", "Thriller"
    ],
    id: 718930,
    original_language: "en",
    original_title: "Bullet Train",
    overview:
      "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
    popularity: 2069.318,
    poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
    release_date: "2022-07-03",
    title: "Bullet Train",
    video: false,
    vote_average: 7.4,
    vote_count: 953,
  },
  {
    adult: false,
    backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
    genres: ["Fantasy", "Action", "Comedy"
    ],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 1869.63,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.8,
    vote_count: 3832,
  },
  {
    adult: false,
    backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
    genres: ["Action", "Drama", "Science Fiction"
    ],
    id: 629176,
    original_language: "en",
    original_title: "Samaritan",
    overview:
      "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
    popularity: 1831.672,
    poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
    release_date: "2022-08-25",
    title: "Samaritan",
    video: false,
    vote_average: 7,
    vote_count: 1160,
  },
  {
    adult: false,
    backdrop_path: "/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg",
    genres: ["Fantasy", "Action", "Adventure"
    ],
    id: 960700,
    original_language: "ja",
    original_title: "鋼の錬金術師 完結編 復讐者スカー",
    overview:
      "In this sequel to the 2017 live-action netflix Adaptation of the manga the Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
    popularity: 1812.212,
    poster_path: "/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg",
    release_date: "2022-05-20",
    title: "Fullmetal Alchemist: The Revenge of Scar",
    video: false,
    vote_average: 7,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
    genres: ["Romance", "Drama"
    ],
    id: 744276,
    original_language: "en",
    original_title: "After Ever Happy",
    overview:
      "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
    popularity: 1668.502,
    poster_path: "/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg",
    release_date: "2022-08-24",
    title: "After Ever Happy",
    video: false,
    vote_average: 6.2,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/d3l7kgFJyLTTQSrR4ysCk5yeVyW.jpg",
    genres: ["Action", "Drama"
    ],
    id: 579974,
    original_language: "te",
    original_title: "రౌద్రం రణం రుధిరం",
    overview:
      "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    popularity: 1659.728,
    poster_path: "/wE0I6efAW4cDDmZQWtwZMOW44EJ.jpg",
    release_date: "2022-03-24",
    title: "RRR",
    video: false,
    vote_average: 7.8,
    vote_count: 381,
  },

  {
    adult: false,
    backdrop_path: "/2RSirqZG949GuRwN38MYCIGG4Od.jpg",
    genres: [ "Thriller"
    ],
    id: 985939,
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights",
    popularity: 5402.19,
    poster_path: "/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
    release_date: "2022-08-11",
    title: "Fall",
    video: false,
    vote_average: 7.5,
    vote_count: 1053,
  },
  {
    adult: false,
    backdrop_path: "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
    genres: ["Fantasy", "Adventure", "Family"
    ],
    id: 532639,
    original_language: "en",
    original_title: "Pinocchio",
    overview:
      "A wooden puppet embarks on a thrilling adventure to become a real boy.",
    popularity: 2859.481,
    poster_path: "/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg",
    release_date: "2022-09-07",
    title: "Pinocchio",
    video: false,
    vote_average: 6.8,
    vote_count: 739,
  },
  {
    adult: false,
    backdrop_path: "/ybvm31ae8WW5O6411PDzwFlETuq.jpg",
    genres: ["Adventure", "Drama", "Horror"
    ],
    id: 760741,
    original_language: "en",
    original_title: "Beast",
    overview:
      "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    popularity: 2651.33,
    poster_path: "/iRV0IB5xQeOymuGGUBarTecQVAl.jpg",
    release_date: "2022-08-11",
    title: "Beast",
    video: false,
    vote_average: 7.1,
    vote_count: 497,
  },
  {
    adult: false,
    backdrop_path: "/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
    genres: ["Action", "Comedy", "Thriller"
    ],
    id: 718930,
    original_language: "en",
    original_title: "Bullet Train",
    overview:
      "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
    popularity: 2069.318,
    poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
    release_date: "2022-07-03",
    title: "Bullet Train",
    video: false,
    vote_average: 7.4,
    vote_count: 953,
  },
  {
    adult: false,
    backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
    genres: ["Fantasy", "Action", "Comedy"
    ],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 1869.63,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.8,
    vote_count: 3832,
  },
  {
    adult: false,
    backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
    genres: ["Action", "Drama", "Science Fiction"
    ],
    id: 629176,
    original_language: "en",
    original_title: "Samaritan",
    overview:
      "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
    popularity: 1831.672,
    poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
    release_date: "2022-08-25",
    title: "Samaritan",
    video: false,
    vote_average: 7,
    vote_count: 1160,
  },
  {
    adult: false,
    backdrop_path: "/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg",
    genres: ["Fantasy", "Action", "Adventure"
    ],
    id: 960700,
    original_language: "ja",
    original_title: "鋼の錬金術師 完結編 復讐者スカー",
    overview:
      "In this sequel to the 2017 live-action netflix Adaptation of the manga the Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
    popularity: 1812.212,
    poster_path: "/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg",
    release_date: "2022-05-20",
    title: "Fullmetal Alchemist: The Revenge of Scar",
    video: false,
    vote_average: 7,
    vote_count: 115,
  },
  {
    adult: false,
    backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
    genres: ["Romance", "Drama"
    ],
    id: 744276,
    original_language: "en",
    original_title: "After Ever Happy",
    overview:
      "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
    popularity: 1668.502,
    poster_path: "/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg",
    release_date: "2022-08-24",
    title: "After Ever Happy",
    video: false,
    vote_average: 6.2,
    vote_count: 108,
  },
];

export default moviedata;
